language: ruby
rvm:
 - 2.5
 - jruby
install: 
 - bundle install
script:
 - export GALAXY_URL=http://0.0.0.0:3000
 - bundle exec rackup -P rackup.pid -p 3000 -o 0.0.0.0 &
 - bundle exec rake
 - kill `cat rackup.pid`
